// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9uh-KgdDyoj5MfJL159CSQ3Hi6raugI',
    appId: '1:537155870217:web:cb6bd4694e43b1778e62d8',
    messagingSenderId: '537155870217',
    projectId: 'app-treino-b3643',
    authDomain: 'app-treino-b3643.firebaseapp.com',
    storageBucket: 'app-treino-b3643.firebasestorage.app',
    measurementId: 'G-1RD0EMVDVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgJHpm-EPk-HECR-0AAXOYKN5-FJeX7A',
    appId: '1:537155870217:android:e5acaee83548f6f88e62d8',
    messagingSenderId: '537155870217',
    projectId: 'app-treino-b3643',
    storageBucket: 'app-treino-b3643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA11It0Hl650vFwi8uGfq0jtzrEQC7zfHo',
    appId: '1:537155870217:ios:7ddeccabec43f46a8e62d8',
    messagingSenderId: '537155870217',
    projectId: 'app-treino-b3643',
    storageBucket: 'app-treino-b3643.firebasestorage.app',
    iosBundleId: 'com.example.appTreinoPremium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA11It0Hl650vFwi8uGfq0jtzrEQC7zfHo',
    appId: '1:537155870217:ios:7ddeccabec43f46a8e62d8',
    messagingSenderId: '537155870217',
    projectId: 'app-treino-b3643',
    storageBucket: 'app-treino-b3643.firebasestorage.app',
    iosBundleId: 'com.example.appTreinoPremium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_9uh-KgdDyoj5MfJL159CSQ3Hi6raugI',
    appId: '1:537155870217:web:6ea015496457ea788e62d8',
    messagingSenderId: '537155870217',
    projectId: 'app-treino-b3643',
    authDomain: 'app-treino-b3643.firebaseapp.com',
    storageBucket: 'app-treino-b3643.firebasestorage.app',
    measurementId: 'G-H2Q2MRCZZH',
  );
}
